<img src = "https://drive.google.com/uc?export=view&id=1zD1_7Y4Ejud8OsuQb49rHGfl9qhihAh5" alt = "Encabezado MLDS" width = "100%">  </img>

# **Tarea 1 - Introducción al análisis de datos: *Python* y *NumPy***
---
Esta tarea le permitirá practicar y aplicar las habilidades adquiridas para la escritura de código en el lenguaje de programación *Python* y su librería de numérica *NumPy*.

> **Nota:** Esta tarea va a ser calificada en la plataforma **[UNCode](https://juezun.github.io/)**. Para esto, en cada ejercicio se indicará si es calificable o no, también los lugares donde debe escribir su código sin modificar lo demás con un aproximado de cantidad de líneas a escribir. No se preocupe si su código toma más líneas, esto es simplemente un aproximado destinado a que pueda replantear su estrategia si el código está tomando más de las esperadas. No es un requisito estricto y soluciones más largas también son válidas. Al finalizar, para realizar el envío (*submission*), descargue el notebook como un archivo **`.ipynb`** y haga su entrega a través de **Moodle**.

Ejecute las siguientes celdas para importar las librerías y conocer sus respectivas versiones.

In [3]:
import numpy as np

In [4]:
!python --version
print('NumPy', np.__version__)

Python 3.7.11
NumPy 1.19.5


Este material fue realizado con las siguientes versiones:

- Python 3.6.9

- NumPy: 1.19.5

## **1. Conteo de pedidos**
---

Usted es responsable de la recepción de pedidos en un pequeño negocio en crecimiento. Un día, se produce una gran e inusual cantidad de pedidos por lo que decide usar sus habilidades de programación para realizar esta tarea de una manera más eficiente y automática. Para esto, le asigna a cada uno de los $n$ productos distintos del negocio un código con un número entero de $0$ a $n - 1$ como identificador (ID).

Una de las tareas iniciales que desea realizar en su sistema es tomar la lista de pedidos, que cuidadosamente logró convertir y cargar en un formato digital, y conocer la cantidad total de pedidos que se realizó por cada producto. De esta forma, podrá realizar la solicitud respectiva a sus proveedores.

Suponga que, gracias a la codificación de productos realizada, usted puede obtener una lista con todos los IDs de los productos solicitados fácilmente. A continuación, deberá implementar la función **`conteo_pedidos`**. Esta función debe cumplir con la siguiente especificación:

* La función recibirá como argumento la lista original de IDs de todos los productos pedidos: **`pedidos`**.
* Debe generar y retornar un arreglo con el conteo de veces que se realizó el pedido de cada uno de los productos. El número de pedidos del producto con ID $i$ se debe almacenar en la posición $i$ en el arreglo creado.

Tenga en cuenta que el tamaño del arreglo resultante debe corresponder con el identificador con el número mayor en la lista de **`pedidos`**. 


> **Nota:** En este ejercicio se garantiza que la lista ingresada en el momento de la calificación esté compuesta exclusivamente por números enteros entre $0$ y $n - 1$. No obstante, en un escenario real se considera buena práctica validar las posibles entradas del sistema y realizar un análisis de los flujos alternativos que su problema deberá realizar en cada caso posible.

Considere los siguientes ejemplos de ejecución de la función:

```
>>> print(conteo_pedidos(np.array([2, 2, 3, 4, 2, 2])))
[0. 0. 4. 1. 1.]

>>> print(conteo_pedidos(np.array([1, 2, 3])))
[0. 1. 1. 1.]

>>> print(conteo_pedidos(np.array([0])))
[1.]
```

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* Se puede calcular el máximo de un arreglo **`x`** llamando a la función **`np.max(x)`**.
* La función **`np.zeros`** devuelve un arreglo inicializado con ceros.
* Una opción recomendada es recorrer (iterar) el arreglo de **`pedidos`** a medida que construye el arreglo con el conteo.


In [11]:
# FUNCIÓN CALIFICADA: conteo_pedidos(pedidos)
def conteo_pedidos(pedidos):
  """
  pedidos: un arreglo de NumPy con valores enteros no negativos. Contiene IDs de productos pedidos, pueden estar repetidos.

  Retorna un arreglo con el conteo de los IDs del arreglo de pedidos. 
  El arreglo resultante codifica cada conteo en su posición de ID correspondiente.
  """
  ### ESCRIBA SU CÓDIGO AQUÍ ###  
  # Reemplace la palabra None por el código correspondiente
  # ~ 6 líneas de código
  
  # Obtenga el valor máximo del arreglo 'pedidos'
  máximo = np.amax(pedidos);
  # Calcule el tamaño del arreglo resultante 
  tamaño = máximo+1
  # Cree un arreglo de ceros con ese tamaño para la guardar su respuesta
  conteos = np.zeros(tamaño)

  # Recorra cada ID en el arreglo de 'pedidos' e incremente en 1 la cantidad 
  # correspondiente a ese ID en el arreglo de 'conteos' en cada iteración
  for i in pedidos:
    conteos[i] +=1
  ### FIN DEL CÓDIGO ###

  return conteos

In [12]:
# CELDA DE PRUEBAS 
print(conteo_pedidos(np.array([1, 2, 3, 3, 3, 5, 5, 6])))

print(conteo_pedidos(np.array([2, 2, 3, 4])))

print(conteo_pedidos(np.array([1, 2, 3])))

[0. 1. 1. 3. 0. 2. 1.]
[0. 0. 2. 1. 1.]
[0. 1. 1. 1.]


La salida de la celda anterior debería ser:
```
[0. 1. 1. 3. 0. 2. 1.]
[0. 0. 2. 1. 1.]
[0. 1. 1. 1.]
```

## **2. Cantidad de material**
---
Cada producto fabricado en su empresa requiere de una cierta cantidad de unidades de materias primas $M_j$. Usted posee una tabla con la cantidad de unidades de cada material $M_j$ que se requiere para la fabricación de cada producto $P_i$. Al igual que con los productos, cada una de las $m$ materias primas están identificadas con números enteros $j$ entre $0$  y $m - 1$ que corresponden a la posición del arreglo. Usted decide calcular automáticamente la cantidad de materia prima requerida para cumplir con un pedido determinado.

Considere el siguiente ejemplo de un pedido:

* Cantidad de unidades por producto:

| $P_0$ | $P_1$ | $P_2$ | $P_3$ |
|-----|-----|-----|-----|
| 2   | 5   | 7   | 8   |

* Cantidad de material $M_j$ necesario para fabricar el producto $P_i$:

|       | $P_0$ | $P_1$ | $P_2$ | $P_3$ |
|-------|-------|-------|-------|-------|
| $M_0$ | 2     | 0     | 2     | 1     |
| $M_1$ | 1     | 1     | 1     | 0     |
| $M_2$ | 2     | 2     | 0     | 2     |


Por ejemplo, para cumplir con este pedido se requiere el siguiente número de unidades del material $M_0$:
* $4$ unidades del material $M_0$ para fabricar $2$ unidades de $P_0$.
* $14$ unidades del material $M_0$ para fabricar $7$ unidades de $P_2$.
* $8$ unidades del material $M_0$ para fabricar $8$ unidades de $P_3$.

Para un total de $26$ unidades de material $M_0$. Si se repite el proceso para los demás materiales el total de materiales que se deben adquirir para este pedido son:


| $M_0$ | $M_1$ | $M_2$ |
|-----|-----|-----|
| 26   | 14   | 30  |

Para esta actividad deberá implementar la función **`cantidad_material`**, que recibe como argumento:
* Lista de cantidad de unidades por producto: **`productos`**.
* Tabla de cantidades de material por producto **`cantidades`**. 

A partir de estos $2$ arreglos de *NumPy* la función debe retornar el arreglo con la cantidad de cada material del pedido.

Considere el caso anterior en el ejemplo de ejecución de la función:

```
>>> productos = np.array([2, 5, 7, 8])
>>> cantidades = np.array(
    [[2, 0, 2, 1,],
    [1, 1, 1, 0],
    [2, 2, 0, 2]]  
  )
>>> cantidad_material(productos, cantidades)
array([26, 14, 30])
```

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* Tómese su tiempo para comprender el problema. Este problema puede solucionarse de varias formas. Una de ellas es mediante operaciones de **álgebra lineal**. Para más información, considere el uso de operaciones como la **multiplicación matricial** (operador **`@`**) y el **producto punto** (**`np.dot`**) y aplique la solución usando los conceptos vistos en el taller guiado de *NumPy*.

* Otra solución puede ser mediante operaciones entre vectores y agregaciones como la suma con **`np.sum(axis = ?)`**, definiendo como argumento el eje por el cual se debe realizar la suma (0 para filas, 1 para columnas).



In [13]:
# FUNCIÓN CALIFICADA: cantidad_material(productos, cantidades)
def cantidad_material(productos, cantidades):
  """
  productos: un arreglo de NumPy con dimensión (n,) con valores enteros no negativos.
             Contiene la cantidad pedida de cada uno de los productos.
  cantidades: un arreglo de NumPy con dimensión (m, n) con valores enteros no negativos.
              Contiene las unidades de materia prima (filas) necesarias para la 
              fabricación de cada producto (columnas)

  Retorna un arreglo con dimensión (m,) con la cantidad de unidades de materia prima 
  requeridas en el pedido.
  """
  ### ESCRIBA SU CÓDIGO AQUÍ ###  
  # Reemplace la palabra None por el código correspondiente
  # ~ 1-5 líneas de código
  
  # Opere las matrices de entrada para obtener el valor requerido.
  # Tenga en cuenta la dimensión de los arreglos a la hora de realizar las operaciones
  materiales = np.dot(cantidades, productos)
  ### FIN DEL CÓDIGO ###

  return materiales

In [14]:
# CELDA DE PRUEBAS 
productos = np.array([0, 5, 1, 2])

cantidades = np.array(
  [[2, 0, 2, 1,],
  [1, 5, 1, 0],
  [3, 2, 0, 0],
  [2, 2, 0, 2]]  
)

cantidad_material(productos, cantidades)

array([ 4, 26, 10, 14])

La salida de la celda anterior debería ser:
```
array([ 4,  26, 10, 14])
```

## **3. Cálculo de costos**
---
¡Buen trabajo! Con la ayuda de *NumPy* logró obtener el conteo de pedidos por cada producto y la cantidad de material necesario para fabricarlos. Ahora, para fabricar el producto $P_i$ debe realizar un pedido al proveedor de las materias primas necesarias para construirlo. 

La empresa tiene un convenio con el proveedor por medio del cual se aplica un descuento de un porcentaje $D$ en materiales cuando se adquieren por lo menos $L$ unidades.

Por ejemplo, retomando uno de los ejemplos anteriores, teníamos la cantidad de materiales que solicitar al proveedor:

| $M_0$ | $M_1$ | $M_2$ |
|-----|-----|-----|
| 26   | 14   | 30  |

Ahora también conocemos una lista de precios del proveedor por cada material:

| $M_0$ | $M_1$ | $M_2$ |
|-----|-----|-----|
| \$5.0   | \$3.0   | \$4.5  |

En este caso, el valor estipulado en el convenio para $L$ es 15 y el de $D$ de $0.2$ ($20\%$).

Entonces, el costo total del $M_0 = 5.0 \cdot 26 = \$130$. Adicionalmente, dado que se pidieron más de $15$ unidades aplica el descuento del $20\%$ de descuento, para un valor final de \$$104$.

Repetimos el proceso para los demás materiales y obtenemos el siguiente resultado:

| $M_0$ | $M_1$ | $M_2$ |
|-----|-----|-----|
| 104.0   | 42.0   | 108.0  |

Por lo tanto, el costo total del pedido es de \$$254.0$

Su tarea es implementar la función **`costo_pedido`**, que recibe como argumento:

* Lista original de pedidos individuales **`pedidos`**.
* Tabla de cantidades de material por producto **`cantidades`**.
* Lista de costos por material **`costos`**. 
* Descuento $D$ **`descuento`**. (Número real entre $0.0$ y $1.0$)
* Mínimo de tamaño del lote $L$ **`lote`**. (Número entero mayor o igual que $0$)

A partir de esto deberá calcular el **costo total** del pedido.

Considere el siguiente ejemplo de ejecución de la función:

```
>>> pedidos = np.array([0, 0, 1, 2, 2, 2, 2, 2, 3])
>>> cantidades = np.array(
      [[2, 0, 2, 1,],
      [1, 1, 1, 0],
      [2, 2, 0, 2]]  
    )

>>> costos = np.array([5.0, 3.0, 4.5])
>>> coste_pedido(pedidos, cantidades, costos, 0.1, 5)
121.5
```

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* Utilice las funciones **`conteo_pedidos`** y **`cantidad_material`** realizadas en los puntos anteriores.
* Recuerde que con *NumPy* puede realizar multiplicación matricial (con **`@`**) y multiplicación elemento a elemento (con **`*`**).
* Puede utilizar selección condicional para realizar operaciones únicamente en los elementos de un arreglo que cumplan una determinada condición.
* La selección condicional sólo requiere que el arreglo tenga la misma dimensión que en el que se realiza la operación. No es necesario que la condición realizada sea con el mismo arreglo.
* El descuento $D$ es un número entre $0.0$ y $1.0$ que se tiene que descontar del total del precio de un material.



In [35]:
# FUNCIÓN CALIFICADA: costo_pedido(pedidos, cantidades, costos, descuento, lote)
def costo_pedido(pedidos, cantidades, costos, descuento, lote):
  """
  pedidos: un arreglo de NumPy con valores enteros no negativos entre 0 y n - 1.
  cantidades: un arreglo de NumPy con dimensión (m, n) con valores enteros no negativos.
  costos: un arreglo de NumPy con dimensión (m, ) con valores reales no negativos.
  descuento: un número real entre 0.0 y 1.0
  lote: un número entero no negativo.

  Retorna un número real no negativo con el costo total del pedido.
  """
  ### ESCRIBA SU CÓDIGO AQUÍ ###  
  # Reemplace la palabra None por el código correspondiente
  # ~ 5-7 líneas de código

  productos = conteo_pedidos(pedidos) # Genere el arreglo de conteo de productos.
  materiales = cantidad_material(productos,cantidades) # Genere el arreglo de cantidad de unidades por material.
  for x in range(len(materiales)):
    if (materiales[x] >= lote):
      materiales[x] *= 1-descuento
  costos_pedido = np.dot(costos,materiales) # Opere las matrices para obtener el costo total por material.
  # Realice la operación de descuento utilizando la condición de lote mínimo.
  
  
  costo_total = costos_pedido # Calcule el costo total del pedido con los descuentos aplicados.
  ### FIN DEL CÓDIGO ###
  return costo_total

In [36]:
# CELDA DE PRUEBAS 
pedidos = np.array([0, 0, 1, 2, 2, 2, 2])
cantidades = np.array(
    [[2, 3, 2],
    [1, 5, 1]]  
  )
costos = np.array([5.0, 3.0])

costo_pedido(pedidos, cantidades, costos, 0.2, 15)

93.0

La salida de la celda anterior debería ser:
```
93.0
```

**¡Felicitaciones!** Ha terminado la tarea de la Unidad 1. ¡Excelente trabajo!

## **Entrega**
Para entregar el notebook por favor haga lo siguiente:
1. Descargue el notebook (`Archivo` -> `Descargar .ipynb`).
2. Ingrese a Moodle.
3. Realice el envío del *notebook* que descargó en la tarea (o quiz) correspondiente.
4. Recuerde que si tiene algún error, puede hacer múltiples intentos de envío en *UNCode*. 

## **Créditos**

* **Profesor:** [Felipe Restrepo Calle](https://dis.unal.edu.co/~ferestrepoca/)
* **Asistente docente:** Alberto Nicolai Romero Martínez
  
**Universidad Nacional de Colombia** - *Facultad de Ingeniería*